# Generated by Django 4.1.3 on 2022-11-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('type_grid', 'event', 'action', 'shot_type', 'player', 'zone', 'game', 'period', 'minutes_remaining', 'location_x', 'location_y', 'seconds_remaining', 'distance', 'is_attempted', 'is_made')},
        ),
    ]
